### ISSUE TITLE
Хуйня, переделывай через notifiers NotificationHandler

### ISSUE THREAD

**Issue by Bess3** [VanadisOdr/sendlogmail#2]

**Comment by VanadisOdr** [comment]
Готово

**Comment by VanadisOdr** [comment]
Готово

**Comment by VanadisOdr** [comment]
params_mail = {
    "from": os.getenv('MAIL2'),
    "to": os.getenv('MAIL'),
    "host": "smtp.mail.ru",
    "port": 465,
    "ssl": True,
    "tls": True,
    "subject": "loguru",
    "username": os.getenv('MAIL2'),
    "password": os.getenv('PASSWORD')
}
